/* =============================================================
   GABARITO - Views de Integracao (Firebird)
   Arquivo : sql/views_real.sql
   ============================================================= */

CREATE OR ALTER VIEW GABARITO_EMPRESAS (
  IDEMPRESA,
  CGC
) AS
SELECT
    c.IDEMPRESA        AS IDEMPRESA,
    TRIM(c.CNPJ)       AS CGC
FROM CONFIGURACAO c
WHERE COALESCE(c.ACOBERTAMENTO, 0) <> -1;

CREATE OR ALTER VIEW GABARITO_FATURAMENTO_MENSAL (
  IDEMPRESA,
  SUBTOTAL,
  DESCONTO,
  TOTAL,
  SUBTOTAL_TROCA,
  DESCONTO_TROCA,
  TOTAL_TROCA,
  MES,
  ANO,
  QTD_VENDAS,
  QTD_TROCAS
) AS
SELECT
    se.IDEMPRESA,
    SUM(CASE WHEN se.STATUS IN (1, 3)   THEN se.SUBTOTAL ELSE 0 END)      AS SUBTOTAL,
    SUM(CASE WHEN se.STATUS IN (1, 3)   THEN se.DESCONTO ELSE 0 END)      AS DESCONTO,
    SUM(CASE WHEN se.STATUS IN (1, 3)   THEN se.VLTOTAL  ELSE 0 END)      AS TOTAL,
    SUM(CASE WHEN se.STATUS IN (40, 43) THEN se.SUBTOTAL ELSE 0 END)      AS SUBTOTAL_TROCA,
    SUM(CASE WHEN se.STATUS IN (40, 43) THEN se.DESCONTO ELSE 0 END)      AS DESCONTO_TROCA,
    SUM(CASE WHEN se.STATUS IN (40, 43) THEN se.VLTOTAL  ELSE 0 END)      AS TOTAL_TROCA,
    EXTRACT(MONTH FROM se.DTSAIDA)                                        AS MES,
    EXTRACT(YEAR FROM se.DTSAIDA)                                         AS ANO,
    COUNT(DISTINCT CASE WHEN se.STATUS IN (1, 3)   THEN se.NRPEDIDO END)  AS QTD_VENDAS,
    COUNT(DISTINCT CASE WHEN se.STATUS IN (40, 43) THEN se.NRPEDIDO END)  AS QTD_TROCAS
FROM
    saidaestoque se
WHERE
    se.STATUS IN (1, 3, 40, 43)
GROUP BY
    se.IDEMPRESA,
    EXTRACT(YEAR FROM se.DTSAIDA),
    EXTRACT(MONTH FROM se.DTSAIDA);

CREATE OR ALTER VIEW GABARITO_CTAPAGAR_GERAL (
    IDEMPRESA,
    NRPEDIDOVALE,
    NRDOC,
    DTALTER,
    DTLOG,
    DTVENC,
    DTPAGTO,
    VALOR,
    TOTAL,
    FORMARECEBIDA,
    FORMAPAGA,
    STATUS,
    NOMEEMPRESA,
    PARCELA,
    CCUSTO,
    HISTORICO,
    CDFORNECEDOR,
    FORNECEDOR,
    NOTAFISCAL,
    ACORDO,
    VLPAGO,
    HORALOG,
    CDCONTA1,
    CONTA1,
    CDDOCUMENTO,
    DOCUMENTO,
    CONTA2,
    CONTA3,
    CONTA4
) AS
SELECT
    a.IDEMPRESA,
    a.NRPEDIDOVALE,
    CAST(a.NRDOC          AS VARCHAR(20)  CHARACTER SET OCTETS) AS NRDOC,
    a.DTALTER,
    a.DTLOG,
    a.DTVENC,
    a.DTPAGTO,
    a.VALOR,
    a.TOTAL,
    CAST(c.RECEBTO        AS VARCHAR(50)  CHARACTER SET OCTETS) AS FORMARECEBIDA,
    CAST(d.RECEBTO        AS VARCHAR(50)  CHARACTER SET OCTETS) AS FORMAPAGA,
    a.STATUS,
    CAST(e.NOMEEMPRESA    AS VARCHAR(60)  CHARACTER SET OCTETS) AS NOMEEMPRESA,
    a.PARCELA,
    a.CCUSTO,
    CAST(a.HISTORICO      AS VARCHAR(255) CHARACTER SET OCTETS) AS HISTORICO,
    h.CDFORNECEDOR,
    CAST(h.FORNECEDOR     AS VARCHAR(50)  CHARACTER SET OCTETS) AS FORNECEDOR,
    CAST(a.NOTAFISCAL     AS VARCHAR(20)  CHARACTER SET OCTETS) AS NOTAFISCAL,
    a.ACORDO,
    a.VLPAGTO                   AS VLPAGO,
    a.HORALOG,
    f.CDCONTA                   AS CDCONTA1,
    CAST(f.CONTA          AS VARCHAR(50)  CHARACTER SET OCTETS) AS CONTA1,
    i.CDDOCUMENTO,
    CAST(i.DOCUMENTO      AS VARCHAR(50)  CHARACTER SET OCTETS) AS DOCUMENTO,
    CAST(j.SUBCONTA       AS VARCHAR(50)  CHARACTER SET OCTETS) AS CONTA2,
    CAST(b.SUBSUBCONTA    AS VARCHAR(50)  CHARACTER SET OCTETS) AS CONTA3,
    CAST(g.SUBSUBSUBCONTA AS VARCHAR(50)  CHARACTER SET OCTETS) AS CONTA4
FROM CTAPAGAR a
    LEFT JOIN RECEBTO          c ON (a.CODPAGTO        = c.CDRECEBTO)
    LEFT JOIN RECEBTO          d ON (a.TPPAGTO         = d.CDRECEBTO)
    LEFT JOIN CONFIGURACAO     e ON (a.IDEMPRESA        = e.IDEMPRESA)
    LEFT JOIN FORNECEDOR       h ON (h.CDFORNECEDOR     = a.CDFORNECEDOR)
    LEFT JOIN CONTAS           f ON (f.CDCONTA          = a.CDCONTA)
    LEFT JOIN TIPODOCUMENTO    i ON (i.CDDOCUMENTO      = a.CDDOCUMENTO)
    LEFT JOIN SUBCONTAS        j ON (j.CDSUBCONTA       = a.CDSUBCONTA)
                                AND (j.CDCONTA          = a.CDCONTA)
    LEFT JOIN SUBSUBCONTAS     b ON (b.CDSUBSUBCONTA    = a.CDSUBSUBCONTA)
                                AND (b.CDSUBCONTA       = a.CDSUBCONTA)
                                AND (b.CDCONTA          = a.CDCONTA)
    LEFT JOIN SUBSUBSUBCONTAS  g ON (g.CDSUBSUBSUBCONTA = a.CDSUBSUBSUBCONTA)
                                AND (g.CDSUBSUBCONTA    = a.CDSUBSUBCONTA)
                                AND (g.CDSUBCONTA       = a.CDSUBCONTA)
                                AND (g.CDCONTA          = a.CDCONTA)
WHERE
    a.STATUS IN (1, 2)
    AND a.DTALTER >= DATEADD(-3 YEAR TO CURRENT_DATE);

CREATE OR ALTER VIEW GABARITO_CTARCEBER_GERAL (
    IDEMPRESA,
    NRPEDIDO,
    NRDOC,
    DTSAIDA,
    DTMOV,
    DTVENC,
    DTCOB,
    VALOR,
    DIVIDA,
    TOTALPG,
    FORMARECEBIDA,
    FORMAPAGA,
    STATUS,
    NOMEEMPRESA,
    VENDEDOR,
    CDCLIENTE,
    CLIENTE,
    CDCAIXA,
    PARCELA,
    ORIGEM,
    CAIXA
) AS
SELECT
    a.IDEMPRESA,
    a.NRPEDIDO,
    CAST(a.NRDOC       AS VARCHAR(15)  CHARACTER SET OCTETS) AS NRDOC,
    b.DTSAIDA,
    a.DTMOV,
    a.DTVENC,
    a.DTCOB,
    a.VALOR,
    a.DIVIDA,
    a.TOTALPG,
    CAST(c.RECEBTO     AS VARCHAR(50)  CHARACTER SET OCTETS) AS FORMARECEBIDA,
    CAST(d.RECEBTO     AS VARCHAR(50)  CHARACTER SET OCTETS) AS FORMAPAGA,
    a.STATUS,
    CAST(e.NOMEEMPRESA AS VARCHAR(60)  CHARACTER SET OCTETS) AS NOMEEMPRESA,
    CAST(f.VENDEDOR    AS VARCHAR(50)  CHARACTER SET OCTETS) AS VENDEDOR,
    g.CDCLIENTE,
    CAST(g.CLIENTE     AS VARCHAR(100) CHARACTER SET OCTETS) AS CLIENTE,
    a.CAIXA                     AS CDCAIXA,
    a.PARCELA,
    CAST(a.ORIGEM      AS VARCHAR(255) CHARACTER SET OCTETS) AS ORIGEM,
    CAST(h.CAIXA       AS VARCHAR(50)  CHARACTER SET OCTETS) AS CAIXA
FROM CTARECEBER a
    LEFT JOIN SAIDAESTOQUE     b ON (a.IDEMPRESA  = b.IDEMPRESA)
                                AND (a.NRPEDIDO   = b.NRPEDIDO)
    LEFT JOIN RECEBTO          c ON (a.CODPAGTO   = c.CDRECEBTO)
    LEFT JOIN RECEBTO          d ON (a.TPPAGTO    = d.CDRECEBTO)
    LEFT JOIN CONFIGURACAO     e ON (a.IDEMPRESA   = e.IDEMPRESA)
    LEFT JOIN VENDEDOR         f ON (b.CDVENDEDOR  = f.CDVENDEDOR)
    LEFT JOIN CLIENTE          g ON (g.CDCLIENTE   = a.CDCLIENTE)
    LEFT JOIN TPCAIXA          h ON (h.CDCAIXA     = a.CAIXA)
WHERE
    a.STATUS IN (1, 2)
    AND a.DTALTER >= DATEADD(-3 YEAR TO CURRENT_DATE);

CREATE OR ALTER VIEW GABARITO_CURVA_ABC(
    CDPRODUTO,
    PRODUTO,
    UNIDADE,
    IDEMPRESA,
    NRPEDIDO,
    IDPRECO,
    CDDEPOSITO,
    DEPOSITO,
    VLUNIT,
    VLCUSTO,
    QTDPRODUTO,
    QTDEATUAL,
    QTDEMINIMA,
    DESCPROD,
    DESCPED,
    TOTAL,
    SUBTOTAL,
    TPENTREGA,
    INATIVO,
    PROMOCAO,
    TABPROMOCAO,
    COD_CENTRAL,
    CDFABRICANTE,
    FABRICANTE,
    CDFORNECEDOR,
    CDGRUPO,
    GRUPO,
    CDTIPO,
    TIPO,
    CDLINHA,
    LINHA,
    CDFAMILIA,
    FAMILIA,
    CDCLIENTE,
    CDVENDEDOR,
    DTSAIDA,
    STATUS,
    VLCOMDESCCOMPROMO,
    VLSEMDESCCOMPROMO,
    VLCOMDESCSEMPROMO,
    VLSEMDESCSEMPROMO,
    FATORCONV,
    VLCUSTO_COMPRA,
    FRETE,
    IPI,
    ICMS,
    MULTCAIXA)
AS
SELECT P.CDPRODUTO, CAST(P.PRODUTO AS VARCHAR(70) CHARACTER SET OCTETS), CAST(P.CDUNIDADE AS VARCHAR(3) CHARACTER SET OCTETS), SE.IDEMPRESA, SE.NRPEDIDO, SP.IDPRECO,
       SP.CDDEPOSITO, CAST(DEP.DEPOSITO AS VARCHAR(30) CHARACTER SET OCTETS), COALESCE(SP.VLUNIT,0), IIF(COALESCE(SP.VLCUSTO,0) > 0, SP.VLCUSTO, COALESCE(PP.VLCUSTO,0)),
       COALESCE(SP.QTDPRODUTO*IIF(COALESCE(SP.FATORCONV,0) > 0, SP.FATORCONV, COALESCE(PP.FATORCONV,0)) ,0), COALESCE(MV.QTDEATUAL,0), COALESCE(MV.QTDEMINIMA,0),
       SP.DESCONTO, SE.DESCONTO, SP.TOTAL, SE.SUBTOTAL, SP.STATUS, P.INATIVO, P.PROMOCAO,
       TB.TABPROMOCAO, CAST(P.COD_CENTRAL AS VARCHAR(15) CHARACTER SET OCTETS), P.CDFABRICANTE, CAST(FAB.FABRICANTE AS VARCHAR(50) CHARACTER SET OCTETS), P.CDFORNECEDOR, P.CDGRUPO, CAST(P.GRUPO AS VARCHAR(50) CHARACTER SET OCTETS),
       P.CDTIPO, CAST(P.TIPO AS VARCHAR(50) CHARACTER SET OCTETS), P.CDLINHA, CAST(P.LINHA AS VARCHAR(50) CHARACTER SET OCTETS), P.CDFAMILIA, CAST(P.FAMILIA AS VARCHAR(70) CHARACTER SET OCTETS), SE.CDCLIENTE, SE.CDVENDEDOR, SE.DTSAIDA, SE.STATUS,
       SP.VLUNIT - IIF(AUX.TOTCOMPROMOCAO <> 0, (COALESCE(SE.DESCONTO,0) * SP.VLUNIT / AUX.TOTCOMPROMOCAO), 0),
       SP.VLUNIT - COALESCE(SP.DESCONTO,0) - IIF(AUX.TOTCOMPROMOCAO <> 0, (COALESCE(SE.DESCONTO,0) * SP.VLUNIT / AUX.TOTCOMPROMOCAO), 0),
       SP.VLUNIT - IIF(AUX.TOTSEMPROMOCAO <> 0, (COALESCE(SE.DESCONTO,0) * SP.VLUNIT / AUX.TOTSEMPROMOCAO), 0),
       SP.VLUNIT - COALESCE(SP.DESCONTO,0) - IIF(AUX.TOTSEMPROMOCAO <> 0, (COALESCE(SE.DESCONTO,0) * SP.VLUNIT / AUX.TOTSEMPROMOCAO), 0),
       IIF(COALESCE(SP.FATORCONV,0) > 0, SP.FATORCONV, COALESCE(PP.FATORCONV,0)),
       COALESCE(PP.vlcustoinicial,0),
       COALESCE(P.FRETE,0), COALESCE(P.IPI,0), COALESCE(P.ICMS,0), COALESCE(P.MULTCAIXA,0)
FROM PRODUTO P
JOIN SAIDAPRODUTO SP ON (P.CDPRODUTO = SP.CDPRODUTO) AND (SP.STATUSSE NOT IN (2,9)) AND (SP.MOSTRAR = -1)
JOIN SAIDAESTOQUE SE ON (SP.IDEMPRESA = SE.IDEMPRESA) AND (SP.NRPEDIDO = SE.NRPEDIDO) AND (SE.STATUS IN (1,3,40,43)) AND (SE.DTSAIDA >= DATEADD(-3 YEAR TO CURRENT_DATE))
JOIN MOVIMENTO MV ON (SP.CDPRODUTO = MV.CDPRODUTO) AND (SP.CDDEPOSITO = MV.CDDEPOSITO)
JOIN TABELAPRECO TB ON (SP.IDPRECO = TB.IDPRECO)
LEFT JOIN PRODUTOPRECO PP ON (SP.CDPRODUTO = PP.CDPRODUTO) AND (SP.IDPRECO = PP.IDPRECO) AND (SP.UNID = PP.CDUNIDADE)
LEFT JOIN FABRICANTE FAB ON (P.CDFABRICANTE = FAB.CDFABRICANTE)
LEFT JOIN DEPOSITO DEP ON (SP.CDDEPOSITO = DEP.CDDEPOSITO)
JOIN V_CURVA_AUXILIAR AUX ON (SE.IDEMPRESA = AUX.IDEMPRESA) AND (SE.NRPEDIDO = AUX.NRPEDIDO)
;

CREATE OR ALTER VIEW GABARITO_ENTRADAS (
    NOTAFISCAL,
    DTNOTAFISCAL,
    DTENTRADA,
    CDPRODUTO,
    DESCRICAO,
    QTDE,
    VLCUSTO,
    IDEMPRESA,
    IDENTRADA,
    EMPRESA,
    TOTAL,
    FORNECEDOR,
    CDFORNECEDOR
) AS
SELECT
    CAST(B.NOTAFISCAL AS VARCHAR(10)  CHARACTER SET OCTETS) AS NOTAFISCAL,
    B.DTNTFISCAL                     AS DTNOTAFISCAL,
    B.DTENTRADA,
    A.CDPRODUTO,
    CAST(A.DESCRICAO  AS VARCHAR(150) CHARACTER SET OCTETS) AS DESCRICAO,
    A.QTDE,
    A.VLUNIT                         AS VLCUSTO,
    B.IDEMPRESA,
    B.IDENTRADA,
    CAST(C.NOMEEMPRESA AS VARCHAR(60) CHARACTER SET OCTETS) AS EMPRESA,
    (A.QTDE * A.VLUNIT)              AS TOTAL,
    CAST(D.FORNECEDOR AS VARCHAR(50)  CHARACTER SET OCTETS) AS FORNECEDOR,
    A.CDFORNECEDOR
FROM ENTRPRODUTO A
    JOIN ENTRESTOQUE  B ON (A.IDENTRADA    = B.IDENTRADA)
                       AND (A.IDEMPRESA    = B.IDEMPRESA)
    JOIN CONFIGURACAO C ON (B.IDEMPRESA    = C.IDEMPRESA)
    JOIN FORNECEDOR   D ON (A.CDFORNECEDOR = D.CDFORNECEDOR)
WHERE B.STATUS = 1;

CREATE OR ALTER VIEW GABARITO_VENDEDORES(
    IDEMPRESA,
    CDVENDEDOR,
    NOME_VEND,
    DATA_VENDA,
    TOTAL_VENDAS,
    TOTAL_PEDIDOS,
    CLIENTES_ATENDIDOS,
    TICKET_MEDIO,
    TOTAL_DESCONTO,
    TOTAL_TROCAS,
    QTD_TROCAS,
    QTD_PRODUTOS,
    TOTAL_CUSTO)
AS
SELECT 
    se.idempresa,
    V.CDVENDEDOR,
    CAST(V.VENDEDOR AS VARCHAR(50) CHARACTER SET OCTETS) AS NOME_VEND,
    CAST(se.dtsaida AS DATE) AS DATA_VENDA,
    SUM(CASE WHEN se.status IN (1, 3) THEN se.vltotal ELSE 0 END) AS TOTAL_VENDAS,
    COUNT(DISTINCT CASE WHEN se.status IN (1, 3) THEN se.nrpedido END) AS TOTAL_PEDIDOS,
    COUNT(DISTINCT CASE WHEN se.status IN (1, 3) THEN se.cdcliente END)  AS CLIENTES_ATENDIDOS,
    CASE 
        WHEN COUNT(DISTINCT CASE WHEN se.status IN (1, 3) THEN se.nrpedido END) > 0 
        THEN SUM(CASE WHEN se.status IN (1, 3) THEN se.vltotal ELSE 0 END) / COUNT(DISTINCT CASE WHEN se.status IN (1, 3) THEN se.nrpedido END)
        ELSE 0
    END AS TICKET_MEDIO,
    SUM(CASE WHEN se.status IN (1, 3) THEN COALESCE(se.desconto, 0) ELSE 0 END) AS TOTAL_DESCONTO,
    SUM(CASE WHEN se.status IN (40, 43) THEN se.vltotal ELSE 0 END) AS TOTAL_TROCAS,
    COUNT(DISTINCT CASE WHEN se.status IN (40, 43) THEN se.nrpedido END) AS QTD_TROCAS,
    SUM(COALESCE(sp.total_itens, 0)) AS QTD_PRODUTOS,
    SUM(COALESCE(sp.custo_total_pedido, 0)) AS TOTAL_CUSTO
FROM saidaestoque se
JOIN VENDEDOR V ON V.CDVENDEDOR = SE.CDVENDEDOR
LEFT JOIN (
    SELECT
        idempresa,
        nrpedido,
        SUM(qtdproduto) AS total_itens,
        SUM(COALESCE(vlcusto, 0) * qtdproduto) AS custo_total_pedido
    FROM saidaproduto
    WHERE statusse <> 9
    GROUP BY idempresa, nrpedido
) sp ON sp.nrpedido = se.nrpedido AND sp.idempresa = se.idempresa
WHERE se.status IN (1, 3, 40, 43) AND V.inativo = 0 
GROUP BY se.idempresa, V.CDVENDEDOR, V.VENDEDOR, CAST(se.dtsaida AS DATE);

CREATE OR ALTER VIEW GABARITO_HORARIO (
    IDEMPRESA,
    NOMEEMPRESA,
    DTSAIDA,
    HORARIO,
    HORA,
    VALORPEDIDO,
    NRPEDIDO
) AS
SELECT
    SE.IDEMPRESA,
    CAST(C.NOMEEMPRESA AS VARCHAR(60) CHARACTER SET OCTETS) AS NOMEEMPRESA,
    SE.DTSAIDA,
    SUBSTRING(SE.HORAPED FROM 12 FOR 8)  AS HORARIO,
    EXTRACT(HOUR FROM SE.HORAPED)        AS HORA,
    SE.VLTOTAL                           AS VALORPEDIDO,
    SE.NRPEDIDO
FROM SAIDAESTOQUE SE
    JOIN CONFIGURACAO C ON (SE.IDEMPRESA = C.IDEMPRESA)
WHERE
    SE.STATUS IN (1, 3);
